// <auto-generated />
using System;
using KuliJob.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuliJob.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250713165247_SqliteMigration1")]
    partial class SqliteMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("KuliJob.JobServerEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<long>("LastHeartbeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_heartbeat");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("KuliJob.Storage.Data.CronDb", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT")
                        .HasColumnName("timezone");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_cron");

                    b.ToTable("cron", (string)null);
                });

            modelBuilder.Entity("KuliJob.Storage.Data.JobInputDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_on");

                    b.Property<string>("JobData")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_data");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_name");

                    b.Property<int>("JobState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_state");

                    b.Property<Guid>("JobStateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_state_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Queue")
                        .HasColumnType("TEXT")
                        .HasColumnName("queue");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<int>("RetryDelayMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_delay_ms");

                    b.Property<int>("RetryMaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_max_count");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_name");

                    b.Property<long>("StartAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_after");

                    b.Property<string>("ThrottleKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("throttle_key");

                    b.Property<int>("ThrottleSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("throttle_seconds");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_job_created_on");

                    b.HasIndex("JobName")
                        .HasDatabaseName("ix_job_job_name");

                    b.HasIndex("StartAfter")
                        .HasDatabaseName("ix_job_start_after");

                    b.HasIndex("ThrottleKey")
                        .HasDatabaseName("ix_job_throttle_key");

                    b.ToTable("job", (string)null);
                });

            modelBuilder.Entity("KuliJob.Storage.Data.JobStateDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<int>("JobState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_state");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_job_state");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_job_state_id");

                    b.HasIndex("Id", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_state_id_job_id");

                    b.ToTable("job_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
