name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: ikalnytskyi/action-setup-postgres@v7
      with:
        username: postgres
        password: postgres
        port: 5432
        postgres-version: "15"
      id: postgres
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build
    
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          src/KuliJob.Tests/coveragereport
