name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Run PostgreSQL
      run: |
        docker pull postgres:15
        docker run -d \
          --name postgres-container \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          postgres:15
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build
    
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          src/KuliJob.Tests/coveragereport
